//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcView.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicDataEntities : DbContext
    {
        public ClinicDataEntities()
            : base("name=ClinicDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DoctorByClinic> DoctorByClinics { get; set; }
        public virtual DbSet<Enquiry> Enquiries { get; set; }
        public virtual DbSet<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual DbSet<InvoiceMaster> InvoiceMasters { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<PatientMaster> PatientMasters { get; set; }
        public virtual DbSet<tbl_ClinicDetails> tbl_ClinicDetails { get; set; }
        public virtual DbSet<tbl_DoctorDetails> tbl_DoctorDetails { get; set; }
        public virtual DbSet<tblEmployeeBankDetail> tblEmployeeBankDetails { get; set; }
        public virtual DbSet<tblEmployeeContactDetail> tblEmployeeContactDetails { get; set; }
        public virtual DbSet<tblEmployeeOtherDetail> tblEmployeeOtherDetails { get; set; }
        public virtual DbSet<tblEmployeePersonal> tblEmployeePersonals { get; set; }
        public virtual DbSet<EnquiryBackup_17062023> EnquiryBackup_17062023 { get; set; }
        public virtual DbSet<EnquiryBackup14102021> EnquiryBackup14102021 { get; set; }
        public virtual DbSet<tbl_DoctorDetailsBackup_17062023> tbl_DoctorDetailsBackup_17062023 { get; set; }
        public virtual DbSet<tbl_DoctorDetailsBackup_170620232> tbl_DoctorDetailsBackup_170620232 { get; set; }
    }
}
